export const algorithmDisplayNames = {
	avlTree: 'AVL fa',
	bTree: 'B fa',
	bellmanFordShortestPath: 'Bellman-Ford legrövidebb út',
	binaryHeap: 'Bináris kupac',
	binaryTree: 'Bináris fa',
	jarvisMarch: "Jarvis menetelés",
	coinChange: 'Pénzváltó algoritmus',
	convexHull: 'Konvex burok (brute force)',
	dijkstraShortestPath: 'Dijkstra legrövidebb út',
	factorialCalculator: 'Faktoriális számítás',
	fractionalKnapsack: 'Töredekes hátizsák (ismétlés nélkül)',
	fractionalKnapsackRep: 'Töredekes hátizsák (ismétléssel)',
	grahamScan: "Graham szkennelése",
	heapSort: 'Kupacrendezés',
	hilbertCurves: 'Hilbert görbék',
	insertionSort: 'Beszúró rendezés',
	knuthMorrisPratt: 'Knuth-Morris-Pratt algoritmus',
	kruskalMinimumSpanningTree: 'Kruskal algoritmus',
	maxSumPath: 'Legnagyobb összegű út',
	mergeSort: 'Összefésülő rendezés',
	primMinimumSpanningTree: 'Prim algoritmus',
	quickSort: 'Gyorsrendezés',
	rabinKarp: 'Rabin-Karp algoritmus',
	redBlackTree: 'Piros-Fekete fa',
	towersOfHanoi: 'Hanoi tornyai',
	travelingProblem: 'Utazás probléma (Mohó)',
};
